import { Project } from '../types';

export const projectsData: Project[] = [
  {
    id: 'interview-prep-ai',
    name: 'AI-Powered Interview Preparation & Placement Assistant',
    status: 'Under Development',
    isFeatured: true,
    category: ['Java', 'Spring Boot', 'Full Stack'],
    shortDescription:
      'An AI-powered platform designed to help candidates prepare for technical interviews through resume analysis, adaptive mock interviews, answer evaluation, interview planning, and personalized practice.',
    fullOverview:
      'A comprehensive career placement and interview training system that simulates technical engineering interviews. Candidates can upload their resumes to receive tailored assessment pathways, dynamic follow-up questioning generated by backend AI pipelines, and objective score breakdowns on system design, algorithms, and core domain knowledge.',
    problemSolved:
      'Job seekers often struggle with unstructured technical preparation and lack realistic, real-time feedback before official interviews. This platform bridges that gap by offering contextual question generation tailored to exact candidate resumes and skill profiles.',
    architecture:
      'Engineered with a Spring Boot RESTful micro-backend, leveraging JPA/Hibernate for relational persistence in MySQL. Integrated with modern AI API endpoints for question generation and prompt-based semantic answer grading, paired with a React.js client interface.',
    technologies: ['Java', 'Spring Boot', 'MySQL', 'REST API', 'React.js', 'AI API', 'Git'],
    features: [
      'Resume upload & automated text extraction',
      'Resume analysis & skill gap identification',
      'AI-generated interview questions based on candidate profile',
      'Adaptive interview difficulty tailored to candidate responses',
      'Detailed answer evaluation and scoring rubric',
      'Structured interview planning & preparation timelines',
      'Historical interview archives & performance analytics',
      'Personalized domain practice (Data Structures, OOP, SQL, System Architecture)'
    ],
    githubUrl: 'https://github.com/Atharvk04/ai-powered-interview-prep',
    liveUrl: '#',
    badge: 'Featured Project'
  },
  {
    id: 'online-shopping-cart',
    name: 'Online Shopping Cart',
    category: ['Java', 'Web'],
    shortDescription:
      'Java-based shopping cart application with customer and admin functionality, database integration, authentication, and product management.',
    fullOverview:
      'A full-featured e-commerce web platform engineered using standard Java web technologies. It provides seamless catalog browsing, session-based cart management, automated order checkout flows, and a protected administrative back-office panel.',
    problemSolved:
      'Demonstrates secure session handling, relational transactional data consistency, and role-based access control (Admin vs Customer) in standard enterprise Java applications.',
    architecture:
      'Built using Java Servlets for request handling, JSP and JSTL for server-side dynamic rendering, and JDBC for raw transactional interaction with a relational MySQL schema.',
    technologies: ['Java', 'JSP', 'Servlet', 'JDBC', 'MySQL', 'HTML', 'CSS'],
    features: [
      'Customer registration and secure authentication flow',
      'Dynamic product catalog with category filtering',
      'Session-managed interactive shopping cart',
      'Admin portal for inventory, category, and order management',
      'Complete CRUD operations on products and orders',
      'Relational database integration with transactional integrity'
    ],
    githubUrl: 'https://github.com/Atharvk04/ShoppingCart',
    liveUrl: '#'
  },
  {
    id: 'home-automation-system',
    name: 'Home Automation System',
    category: ['Java', 'Other'],
    shortDescription:
      'A Java-based application designed using object-oriented programming and MVC architecture to manage home automation functionality.',
    fullOverview:
      'A clean software controller for modern smart household components, organizing device states (lighting, HVAC, power outlets, surveillance) via strict Object-Oriented principles and modular design layers.',
    problemSolved:
      'Abstracts diverse simulated hardware devices under unified polymorphic interfaces, allowing decoupled state updates, telemetry logging, and command dispatching.',
    architecture:
      'Organized in a strict Model-View-Controller (MVC) architecture with a Data Access Object (DAO) layer for clean separation between state persistence and business rules.',
    technologies: ['Core Java', 'OOP', 'MVC', 'DAO'],
    features: [
      'MVC architectural separation of concerns',
      'Object-oriented polymorphism for diverse appliance interfaces',
      'Modular device control and status monitoring',
      'DAO layer isolating persistence mechanisms from device state logic',
      'Event-driven command dispatching and fault tolerance'
    ],
    githubUrl: 'https://github.com/Atharvk04/Home-Automation-System',
    liveUrl: '#'
  }
];
